{
    'name': 'Wellcomm',
    'version': '19.0.1.0.0',
    'category': 'Sales/CRM',
    'summary': 'Sincronización de clientes ISP desde Mikrowisp y tableros de indicadores',
    'author': 'Nisbe',
    'depends': ['base', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/zona_caracas_views.xml',
        'views/zona_llanos_views.xml',
        'views/zona_puentehierro_views.xml',
        'views/zona_ocumare_views.xml',
        'views/mikrowisp_dashboard_estado_views.xml',
        'views/mikrowisp_dashboard_deuda_views.xml',
        'views/mikrowisp_dashboard_recaudacion_views.xml',
        'views/mikrowisp_dashboard_recaudacion_anual_views.xml',
        'views/mikrowisp_dashboard_movimientos_anual_views.xml',
        'views/mikrowisp_estado_log_views.xml',
        'views/mikrowisp_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
