from . import res_partner
from . import mikrowisp_estado_log
from . import mikrowisp_dashboard_estado
from . import mikrowisp_dashboard_recaudacion_anual
from . import mikrowisp_dashboard_movimientos_anual
from . import mikrowisp_factura
from . import mikrowisp_sync
from . import zona_caracas
from . import zona_llanos
from . import zona_puentehierro
from . import zona_ocumare
from . import res_config_settings
